spring:
  application:
    name: microservice-zuul
server:
  context-path: /
  port: 9003

eureka:
  client:
    service-url:
      #集群配置
      defaultZone: http://eureka-server-5001.com:5001/eureka/,http://eureka-server-5002.com:5002/eureka/,http://eureka-server-5003.com:5003/eureka/
  instance:
    instance-id: microservice-zuul-9003.com  #自定义服务名称信息
    prefer-ip-address: true #访问路径上会显示IP,当应用程序向eureka注册时，它将使用其IP地址而不是其主机名。

zuul:
  prefix: /app     #指定一个全局的前缀 
  ignored-services: microservice-dept   #忽略真实服务名
  #ignored-services: "*"
  routes:
    dept-service:
      service-id: microservice-dept    #真实服务名映射
      path: /mydept/**      