server:
  context-path: /
  port: 7001
  
spring:
  application:
    name: microservice-config-server
  
  cloud:
    config:
      label: master     #配置仓库的分支
      server:
        git:
          uri: https://github.com/hnyydp/microservice-config.git     #配置git仓库地址
          #search-paths: microservice-config/src/main/resources/properties  #配置仓库路径
          ##访问git仓库的用户名密码 公共仓库可以不写，私有仓库需要写
          #username: xxx
          #password: xxx   
