server:
  context-path: /
  port: 5003       #eureka服务端的端口
  
eureka:
  instance:
    appname: eureka-server-5003.com             #eureka服务端的实例名称
  client:
    register-with-eureka: false   #false表示不向注册中心注册自己,因为本身应用就是注册中心
    fetch-registry: false     #false表示自己端就是注册中心，职责就是维护服务实例，并不需要去检索服务
    service-url:
      #设置与Eureka Server交互的地址,查询服务和注册服务都需要依赖这个地址（单机）。
      #defaultZone: http://${eureka.instance.appname}:${server.port}/eureka/
      #集群配置,相互注册
      defaultZone: http://eureka-server-5001.com:5001/eureka/,http://eureka-server-5002.com:5002/eureka/
