server:
  context-path: /
  port: 80
  
spring:
  application:
    name: microservice-dept-consumer-feign  #服务名

eureka:
  client:
    service-url:
      #集群配置
      defaultZone: http://eureka-server-5001.com:5001/eureka/,http://eureka-server-5002.com:5002/eureka/,http://eureka-server-5003.com:5003/eureka/